enum Reason {
  // User
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_INVALID = 'USER_INVALID',
  USER_WITH_SUBSCRIPTION = 'USER_WITH_SUBSCRIPTION',
  USER_CUSTOM_REF_TAG_OCCUPIED = 'USER_CUSTOM_REF_TAG_OCCUPIED',
  USER_EMAIL_OCCUPIED = 'USER_EMAIL_OCCUPIED',
  USER_TELEGRAM_OCCUPIED = 'USER_TELEGRAM_OCCUPIED',

  EMAIL_CODE_INVALID = 'EMAIL_CODE_INVALID',
  TELEGRAM_AUTH_INVALID = 'TELEGRAM_AUTH_INVALID',
  REFRESH_TOKEN_INVALID = 'REFRESH_TOKEN_INVALID',
  RESET_TOKEN_EXPIRED = 'RESET_TOKEN_EXPIRED',
  RESET_TOKEN_INVALID = 'RESET_TOKEN_INVALID',
}
export default Reason;
export { Reason as R };
